### ISSUE TITLE
【画面遷移】ホーム → 商品詳細

### ISSUE THREAD

**Issue by shunsuke-tamura** [scla-sagauniv/tumaguro#35]
ホームからクエリパラメータで選択されたidを渡す
例）/product_details?id='000000001'

1. ホームから商品を選択する
2. クエリパラメータにidを入れて/product_detailsに遷移する
3. 商品詳細画面を渡されたidに合った商品で描画する

**Comment by tt1125** [comment]
# home/script.js
  
import products from "../static/db.js";

const itemsContainer = document.getElementById("item-list-container");

for (const product of products) {

  const rink = document.createElement("a")
  rink.href = `../product_details/?id=${product.id}`


  const gridItem = document.createElement("div");
  gridItem.classList.add("grid-item");

  const img = document.createElement("img");
  img.classList.add("product-image");
  img.src = `../static/${product.img}`;

  const h3 = document.createElement("h3");
  h3.textContent = product.title;

  const price = document.createElement("p");
  price.classList.add("product-price");
  price.textContent = `¥${product.price}`;

  const review = document.createElement("p");
  const star = document.createElement("span");
  star.classList.add("star5_rating");
  star.setAttribute("data-rate", product.review);
  const reviewNum = document.createTextNode(`(${product.reviewNum}件)`);
  review.appendChild(star);
  review.appendChild(reviewNum);

  gridItem.appendChild(img);
  gridItem.appendChild(h3);
  gridItem.appendChild(price);
  gridItem.appendChild(review);
  rink.appendChild(gridItem);

  itemsContainer.appendChild(rink);
}

**Comment by yuuki1005** [comment]
#完成
‘‘‘javascript
import products from "../static/db.js";
// const url = new URL('http://127.0.0.1:5500/product_details/?id=00000000001');
const url = new URL(location.href);
const params = new URLSearchParams(url.search);
const id = params.get('id');
const productIndex = products.findIndex((e) => e.id === id);
const product = products[productIndex];

const titleElent = document.getElementsByClassName("detail-title")[0]
titleElent.textContent = `${product.title}`;

const detailimg = document.getElementsByClassName("detail-img")[0]
detailimg.src = `../static/${product.img}`;

const p=document.getElementsByClassName("star")[0]
const span=document.getElementsByClassName("star5_rating")[0]
const t=document.createTextNode( `(${product.reviewNum}件)`)
p.textContent =""
span.setAttribute("data-rate",`${product.review}`)
p.appendChild(span)
p.appendChild(t)

const price = document.getElementsByClassName("detail-price")[0]
price.textContent = `¥${product.price}`;

const company = document.getElementsByClassName("company")[0]
company.textContent = `${product.from}`;
```
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>ほげほげショッピング</title>
  <link rel="stylesheet" type="text/css" href="style.css" />
</head>

<body>
  <div class="detail-wrap">
    <img class="detail-img" src="static/test.png" alt="商品画像">
    <div class="detail-info">
      <p class="detail-title">商品1</p class="detail-title">
      <p class="company">ほげほげカンパニー</p>
      <p class="star">
        <span class="star5_rating" data-rate="3.5"></span>(32件)</p>
      <hr class="detail-line margin-top">
      <p class="detail-price">￥1500</p>
      <div class="detail-line-wrap">
        <hr class="detail-line">
      </div>
      <div class="detail-button-wrap margin-top">
        <button>カートに入れる</button>
      </div>
    </div>
  </div>
</body>
<script type="module" src="./script.js"></script>
</html>
```
